### ISSUE TITLE
Can't request an offline user's profile

### ISSUE THREAD

**Issue by harb00** [80O/PlusEMU#140]
**Describe the bug**
You can't request a user profile when the user is offline.

**To Reproduce**
1. Search for any user who's offline
2. Click on their profile

**Expected behavior**
Their profile is expected to show without error

**Screenshots**

![friendlist1](https://user-images.githubusercontent.com/110241339/182573333-a7f7d57e-5bc3-4129-8bfa-6360887ec49e.gif)
![friendlist2](https://user-images.githubusercontent.com/110241339/182573340-0730aa60-d101-4292-926b-dee7803348fc.gif)

**Comment by kenny577** [comment]
Have you tried this issue on Flash version?

**Comment by harb00** [comment]
No and I won't, but others are welcome to test it on Flash and report back😀

**Comment by Diddyy** [comment]
This is also an issue on Flash. I will look into it now

**Comment by 80O** [comment]
Might be related to Plus caching Habbo instances. Its been disabled in `PlusEnvironment.Habbo GetHabboById(int userId)`

Standard Habbo info might be better wrapped in another data structure (username, figure, gender, motto, online status, registration date & last login time) and queried when needed (lookup first for online users, if offline query from database)

**Comment by Diddyy** [comment]
@harb00 this has been resolved now! :)
@80O Please close this issue! :)
