### ISSUE TITLE
NullReferenceException when switching between rooms

### ISSUE THREAD

**Issue by leolkr** [80O/PlusEMU#177]
When switching between rooms an Exception is raised at RoomUserManager.cs:line 282 
When continuing you will enter the room without any problems.

1. Enter a room
2. Switch to another room
3. Boom.

Exception:
System.NullReferenceException: Object reference not set to an instance of an object.
   at Plus.HabboHotel.Rooms.RoomUserManager.RemoveUserFromRoom(GameClient session, Boolean nofityUser, Boolean notifyKick)

**Comment by leolkr** [comment]
The Exception also happens when a User disconnects.

**Comment by Diddyy** [comment]
I need to set back up a local dev environment so I can have a deeper look but looks like it is potentially an issue with this line.
`dbClient.Execute("UPDATE user_roomvisits SET exit_timestamp = @exitTimestamp WHERE room_id = @roomId AND user_id = @userId ORDER BY exit_timestamp DESC LIMIT 1",`

**Comment by 80O** [comment]
Resolved for now.
