### ISSUE TITLE
No rights in the rooms

### ISSUE THREAD

**Issue by Poumpilop** [80O/PlusEMU#194]
**Describe the bug**
A player who owns his room / has rights to a room does not have access to the moderation drop-down menu.

**To Reproduce**
1. Go to your room
2. Click on the other player
3. See the menu

**Expected behavior**
it is supposed to appear as in the image below

**Screenshots**
![bugreport](https://github.com/80O/PlusEMU/assets/31546432/4e47336d-ae48-44ff-ada2-26d353213a0c)

**Browser Console Error**
Nothing

If the bug is related to a disconnect, paste the possible related errors from the browsers dev console.

**Emulator Error**
Nothing

** Additional Information ** 

The bug is only present with the nitro version. I started debugging on the emulator side and also looking at the nitro side to find out if it was receiving the information correctly. There is a problem with the update with the flatctrl, nitro correctly receives the line
 `user.SetStatus("flatctrl", "1"); `  with the correct value. 

However when updating in nitro 
`userInfo.targetRoomControllerLevel = roomObject.model.getValue<number>(RoomObjectVariable.FIGURE_FLAT_CONTROL);`

the value is referenced as "NaN" because it has not been updated yet, it is only after that nitro executes this piece of code.

```
if(message instanceof ObjectAvatarFlatControlUpdateMessage)
         {
             model.setValue(RoomObjectVariable.FIGURE_FLAT_CONTROL, message.level);

             return;
         }
```

**Comment by 80O** [comment]
Report the bug to nitro. If it works in flash but not in Nitro, it is a nitro bug.
